#!/usr/bin/env node

var csv = require('to-csv');
var raw = '';

process.stdin.on('readable', function() {
  var chunk = process.stdin.read();
  if (chunk !== null) {
    raw += chunk;
  }
});

process.stdin.on('end', function() {
  var data = JSON.parse(raw);
  process.stdout.write(csv(data));
});